---
title: "Assignment 1"
editor: visual
---

# Instructions

You will be asked to perform some basic data manipulation and analysis tasks. You will likely want to use some functions from the `tidyverse` and `janitor` packages that we've focused on in the course. The d

The data you'll be working with are available at this URL:

`https://clanfear.github.io/ioc_iqa/_data/street_crime.csv`

You'll want to load them into R (perhaps call the object `street_crime`) as we've done before in class. You'll probably want to take a quick look at them to get an idea for what is there. These data describe 300 adults and juveniles convicted of particular types of crime and receiving different lengths of sentences. It contains the following measures:

-   `sex`: Recorded sex of the individual

-   `age`: Age of individual at time of sentencing

-   `crime_type`: Type of crime they were sentenced for

-   `sentence`: Length of sentence they were given in months (can be 0 if suspended sentence)

# Fundamentals

## Central Tendency

Calculate one **measure of central tendency** for each variable in the dataset. Report that value and explain why you chose that measure

## Running a Cross-Tab

Report the following:

1.  T

Then make a crosstab of X and Y.

# More Challenging

Using the data GHGH, make a scatter plot of X and Y using `ggplot2`.

Interpret the linear regression output below.

# Harder Problems

## DAG to Estimator

Given this DAG and the data here:

Run a linear model that identifies the effect of X on Y

```{r}

```
